# Generated by Django 4.2.2 on 2023-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_answer_subject_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
