# Generated by Django 4.2.2 on 2023-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_answer_modify_date_question_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
