# Generated by Django 4.2.2 on 2023-06-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tour/images/%Y/%m/%d/'),
        ),
    ]
